sets.exported={
    main="Tauret",
    sub={ name="Shijo", augments={'DEX+15','"Dual Wield"+5','"Triple Atk."+2',}},
    ammo="Yamarang",
    head="Malignance Chapeau",
    body={ name="Herculean Vest", augments={'Enmity+2','AGI+14','"Treasure Hunter"+2','Accuracy+11 Attack+11','Mag. Acc.+5 "Mag.Atk.Bns."+5',}},
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet="Skd. Jambeaux +1",
    neck="Bathy Choker +1",
    waist="Flume Belt +1",
    left_ear="Eabani Earring",
    right_ear="Etiolation Earring",
    left_ring="Moonlight Ring",
    right_ring="Defending Ring",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+1','"Store TP"+10','Damage taken-5%',}},
}